version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    networks:
      - sms-network
  sms-dispatcher:
    image: sms-dispatcher:0.0.1-SNAPSHOT
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=dispatcher
      - DB_USERNAME=dispatcher_user_dbi
      - DB_PASSWORD=dispatcher_password_db
    ports:
      - "8080:8080"
    networks:
      - sms-network
    depends_on:
      - mongodb
networks:
  sms-network:
    driver: custom-driver-1
